=== ponte89/ASWEsame/WebApplication/web/xml-types/anagrafica.xsd
<?xml version="1.0"?>

<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="anagrafica" type="tipo_anagrafica"/>
    <xsd:complexType name="utenti">
        <xsd:sequence>
            <xsd:element name="cliente" type="tipo_cliente" maxOccurs="unbounded" />
            <xsd:element name="admin" type="tipo_admin" maxOccurs="1" />  
            <xsd:element name="cuoco" type="tipo_cuoco" maxOccurs="1" /> 
        </xsd:sequence> 
    </xsd:complexType>
    
    
    <xs:complexType name="utente">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xsd:complexType name="tipo_admin">
        <xs:complexContent>
            <xs:extension base="utente">
                <xsd:sequence>
                    <xsd:element name="name" type="xs:string"/>
                    <xsd:element name="surname" type="xs:string"/>
                </xsd:sequence>
            </xs:extension>
        </xs:complexContent>
    </xsd:complexType>
    
    
    <xsd:complexType name="tipo_cuoco">
        <xs:complexContent>
            <xs:extension base="utente">
                <xsd:sequence>
                    <xsd:element name="name" type="xs:string"/>
                    <xsd:element name="surname" type="xs:string"/>
                </xsd:sequence>
            </xs:extension>
        </xs:complexContent>
    </xsd:complexType>
    
    
    <xsd:complexType name="tipo_cliente">
        <xs:complexContent>
            <xs:extension base="utente">
                <xsd:sequence>
                    <xsd:element name="name" type="xs:string"/>
                    <xsd:element name="surname" type="xs:string"/>
                    <xsd:element name="mail" type="xs:string"/>
                    <xsd:element name="tel" type="xs:string"/>
                    <xsd:element name="user" type="xs:string"/>
                    <xsd:element name="password" type="xs:string"/>
                    <xsd:element name="address" type="xs:string"/>
                    <xsd:element name="cap" type="xs:string"/>
                    <xsd:element name="country" type="xs:string"/>
                </xsd:sequence>
            </xs:extension>
        </xs:complexContent>
    </xsd:complexType>
    
</xsd:schema>

=== ponte89/ASWEsame/WebApplication/web/WEB-INF/xml/anagrafica_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<anagrafica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml-types/anagrafica.xsd">
    <utenti>
        <admin>
            <name>admin</name>
            <surname>admin</surname>
            <username>admin</username>
            <password>admin</password>
        </admin>
        
        <cuoco>
            <name>cuoco1</name>
            <surname>cuoco1</surname>
            <username>cuoco1</username>
            <password>cuoco1</password>
        </cuoco>
        
        <cuoco>
            <name>cuoco2</name>
            <surname>cuoco2</surname>
            <username>cuoco2</username>
            <password>cuoco2</password>
        </cuoco>
        
        <utente>
            <name>utente1</name>
            <surname>utente1</surname>
            <mail>utente1@utente.com</mail>
            <tel>utente1 tel</tel>
            <username>utente1</username>
            <password>utente1</password>
            <address>utente1 indirizzo</address>
            <cap>utente1 cap</cap>
            <country>utente1 country</country>
        </utente>
        
        <utente>
            <name>utente2</name>
            <surname>utente2</surname>
            <mail>utente2@utente.com</mail>
            <tel>utente2 tel</tel>
            <username>utente2</username>
            <password>utente2</password>
            <address>utente2 indirizzo</address>
            <cap>utente2 cap</cap>
            <country>utente2 country</country>
        </utente>
    </utenti>
</anagrafica>
